# Generated by actuent-sdk/scripts/gen_types.mjs from https://agents.actuent.ai/api/mcp (tools/list). Don't edit by hand.
from typing import Any, Dict, List, Literal, TypedDict, Union

class AboutArgs(TypedDict, total=False):
    """Everything About One Thing"""
    name: str

class AboutResult(TypedDict, total=False):
    """What actuent_about returns"""
    pass

class AccountArgs(TypedDict, total=False):
    """Search History and Accounts"""
    kind: Literal["history", "accounts", "preferences"]
    remember: List[str]
    home_city: str
    currency: str
    forget: List[str]
    action: str
    limit: float
    domain: str

class AccountResult(TypedDict, total=False):
    """What actuent_account returns"""
    pass

class ActionsArgs(TypedDict, total=False):
    """Site Actions"""
    domain: str
    action_id: str
    input: Union[Dict[str, Any], str, float]
    mode: Literal["execute", "quote"]
    confirmed: bool
    repeat: bool
    status_url: str

class ActionsResult(TypedDict, total=False):
    """What actuent_actions returns"""
    pass

class CartArgs(TypedDict, total=False):
    """Build a Checkout Link"""
    items: List[Dict[str, Any]]
    user_currency: str

class CartResult(TypedDict, total=False):
    """What actuent_cart returns"""
    pass

class CompareArgs(TypedDict, total=False):
    """Compare Sites or Products"""
    domains: List[str]
    products: List[str]
    user_currency: str

class CompareResult(TypedDict, total=False):
    """What actuent_compare returns"""
    pass

class ContactBusinessArgs(TypedDict, total=False):
    """Contact a Business"""
    action: Literal["send", "status"]
    domain: str
    kind: Literal["question", "message", "booking_request"]
    text: str
    from_name: str
    reply_to: str
    date: str
    time: str
    party_size: float
    confirmed: bool
    status_token: str

class ContactBusinessResult(TypedDict, total=False):
    """What actuent_contact_business returns"""
    pass

class EventsArgs(TypedDict, total=False):
    """Find Events"""
    user_location: str
    preferences: List[str]
    location: str
    query: str
    to: str
    when: Literal["tonight", "today", "tomorrow", "this weekend", "next weekend", "this week", "next week"]
    online: bool
    max_results: float
    user_currency: str

class EventsResult(TypedDict, total=False):
    """What actuent_events returns"""
    location: Union[str, None]
    to: str
    events_found: float
    share_url: str
    message: str
    events: List[Dict[str, Any]]

class FeedbackArgs(TypedDict, total=False):
    """Report a Wrong Answer"""
    tool: str
    question: str
    problem: str
    expected: str

class FeedbackResult(TypedDict, total=False):
    """What actuent_feedback returns"""
    pass

class GetPageArgs(TypedDict, total=False):
    """Read a Page or Site"""
    url: str
    size: str
    domain: str
    question: str
    user_currency: str

class GetPageResult(TypedDict, total=False):
    """What actuent_get_page returns"""
    pass

class NearbyArgs(TypedDict, total=False):
    """Places Nearby"""
    kind: Literal["places", "service"]
    user_location: str
    preferences: List[str]
    query: str
    location: str
    radius_metres: float
    open_now: bool
    filters: List[Literal["vegan", "vegetarian", "gluten_free", "wheelchair", "outdoor_seating", "wifi", "kids", "dogs"]]
    max_price: float
    currency: str
    user_currency: str

class NearbyResult(TypedDict, total=False):
    """What actuent_nearby returns"""
    city: str
    places_found: float
    message: str
    places: List[Dict[str, Any]]

class PlanArgs(TypedDict, total=False):
    """Plan an Evening or Trip"""
    kind: Literal["evening", "trip"]
    user_location: str
    preferences: List[str]
    location: str
    date: str
    start_time: str
    stops: List[str]
    cuisine: str
    filters: List[Literal["vegan", "vegetarian", "gluten_free", "wheelchair", "outdoor_seating", "wifi", "kids", "dogs"]]
    radius_metres: float
    include_events: bool
    days: float
    start_date: str
    user_currency: str

class PlanResult(TypedDict, total=False):
    """What actuent_plan returns"""
    pass

class SearchArgs(TypedDict, total=False):
    """Search the AI Web"""
    kind: Literal["web", "similar", "trending", "news"]
    user_location: str
    preferences: List[str]
    query: str
    category: str
    city: str
    open_now: bool
    sort: Literal["relevance", "popular", "fresh"]
    limit: float
    domain: str
    type: Literal["sites", "queries", "both"]
    topic: str
    user_currency: str

class SearchResult(TypedDict, total=False):
    """What actuent_search returns"""
    query: str
    count: float
    message: str
    results: List[Dict[str, Any]]
    products: List[Dict[str, Any]]
    events: List[Dict[str, Any]]
    answer: Dict[str, Any]
    place_hours: Dict[str, Any]

class WatchArgs(TypedDict, total=False):
    """Watch and Alerts"""
    kind: Literal["price", "page", "new_sites"]
    action: str
    url: str
    target_price_eur: float
    notify: Literal["price", "stock", "both"]
    webhook_url: str
    watch_for: Literal["change", "appears", "disappears"]
    phrase: str
    label: str
    query: str
    user_currency: str

class WatchResult(TypedDict, total=False):
    """What actuent_watch returns"""
    pass

TOOL_NAMES = ["actuent_about", "actuent_account", "actuent_actions", "actuent_cart", "actuent_compare", "actuent_contact_business", "actuent_events", "actuent_feedback", "actuent_get_page", "actuent_nearby", "actuent_plan", "actuent_search", "actuent_watch"]
